/** Renders the SALIS AUTO Build Map from its template plus the generated
 *  control-plane data.
 *
 *      node project-control/build-map/build-map.mjs
 *
 *  Run after `npm run registry` (app/) so the page reads the current registry,
 *  and after `npm run golden` so the golden-path panel reads the current run.
 *  The deck is built the same way — see project-control/tracker/build-deck.mjs.
 *
 *  Why this file exists: the build map was hand-written as a 21 Aug 2026
 *  snapshot and eleven of its twelve headline numbers went stale. The page
 *  itself says a hardcoded count is a defect, so every figure it prints is now
 *  substituted here from a file something else generated.
 *
 *  The ONE exception is remaining effort. Nothing in the repository computes
 *  engineer-days, so those figures live in estimates.json — declared, dated,
 *  and labelled as an estimate on the page beside its date. See that file.
 *
 *  Idempotence: no wall-clock date is read anywhere in this script. Every date
 *  the page prints is the `generatedAt` of the file it came from, so a second
 *  run with unchanged inputs produces byte-identical output. write() still
 *  compares before writing (the same guard app/scripts/build-registry.mjs
 *  uses) so a no-op run touches nothing on disk.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const CONTROL = path.resolve(here, '..')
const REPO = path.resolve(here, '../..')
const APP = path.join(REPO, 'app')

const json = (abs) => JSON.parse(fs.readFileSync(abs, 'utf8'))
const control = (f) => json(path.join(CONTROL, f))

const REG = control('MASTER_REGISTRY.json')
const STATUS = control('STATUS.json')
const BLOCKERS = control('BLOCKERS.json')
const GOLDEN = control('GOLDEN_PATHS.json')
const GATES = control('RELEASE_GATES.json')
const PLAN = control('tracker/plan-structure.json')
const EST = json(path.join(here, 'estimates.json'))

/** The three provenance figures — how many designs, how many spec screens, and
 *  how many names appear in both — are not in MASTER_REGISTRY.json: the
 *  registry stores the *union*, so the overlap it reconciled away is gone by
 *  the time it is written. They are read instead from the generated data the
 *  registry itself reads (`// GENERATED by scripts/port-design-data.mjs — do
 *  not edit by hand`), which is still a measurement rather than a
 *  transcription. Same for the RBAC matrix's shape and the fixture tables.
 *  Parsing mirrors build-registry.mjs's `literal`: these files are a JSON
 *  literal after the `= `, so this is exact rather than a regex guess. */
const readApp = (rel) => fs.readFileSync(path.join(APP, rel), 'utf8')
const literal = (rel) => {
  const s = readApp(rel)
  const i = s.indexOf('= [') >= 0 ? s.indexOf('= [') : s.indexOf('= {')
  const open = s[i + 2]
  const close = open === '[' ? s.lastIndexOf(']') : s.lastIndexOf('}')
  return JSON.parse(s.slice(i + 2, close + 1))
}
const pickObject = (src, name) => {
  const start = src.indexOf(`export const ${name}`)
  const brace = src.indexOf('{', start)
  let depth = 0
  for (let i = brace; i < src.length; i++) {
    if (src[i] === '{') depth++
    else if (src[i] === '}' && --depth === 0) return JSON.parse(src.slice(brace, i + 1))
  }
  throw new Error(`could not read ${name}`)
}

const DESIGN_SCREENS = literal('src/data/generated/screens.ts')
const SPEC_SCREENS = literal('src/data/generated/spec-screens.ts')
const AR = literal('src/data/generated/ar.ts')
const rbacSrc = readApp('src/data/generated/rbac.ts')
const ROLES = JSON.parse(rbacSrc.slice(rbacSrc.indexOf('['), rbacSrc.indexOf('\n]') + 2))
const PERMS = pickObject(rbacSrc, 'PERMS')
const MOCK_TABLES = (readApp('src/data/generated/tables.ts').match(/^export const \w+/gm) || []).length

// ── helpers ──────────────────────────────────────────────────────────────────

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
const n = (x) => Number(x).toLocaleString('en-US')
const pct = (a, b) => (b ? Math.round((a / b) * 100) : 0)
const WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
  'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen',
  'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three',
  'twenty-four', 'twenty-five', 'twenty-six', 'twenty-seven', 'twenty-eight',
  'twenty-nine', 'thirty']
/** Headline prose reads better spelled out, but a spelled-out number must move
 *  with the data like every other one, so it is derived and never typed. */
const word = (v) => (WORDS[v] ?? String(v))
const Word = (v) => { const w = word(v); return w[0].toUpperCase() + w.slice(1) }
/** ISO stamp (date, or full timestamp) → "1 Sep 2026". Purely a reformat of a
 *  value that came out of an input file; no clock is read. */
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const day = (stamp) => {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(stamp))
  if (!m) throw new Error(`unreadable date stamp: ${stamp}`)
  return `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${m[1]}`
}

const T = REG.totals
const CAPS = T.capabilities

// ── provenance ───────────────────────────────────────────────────────────────

const specOverlap = SPEC_SCREENS.filter((s) => s.designScreen).length
const specOnly = SPEC_SCREENS.length - specOverlap
const designFiles = new Set(REG.entries.map((e) => e.designSource).filter(Boolean)).size
const mobileDesigns = REG.entries.filter((e) => e.designMobileSource).length
const designEntries = REG.entries.filter((e) => (e.source || []).includes('design')).length
if (DESIGN_SCREENS.length + specOnly !== CAPS) {
  throw new Error(`provenance does not reconcile: ${DESIGN_SCREENS.length} + ${specOnly} != ${CAPS}`)
}

// ── surfaces ─────────────────────────────────────────────────────────────────

const SURFACE_LABEL = { 'call-center': 'call-centre', 'customer-app': 'customer app' }
const surfaces = Object.entries(STATUS.bySurface).sort((a, b) => b[1].total - a[1].total)
const surfaceList = surfaces.map(([k]) => SURFACE_LABEL[k] || k).join(' · ')

// ── waves ────────────────────────────────────────────────────────────────────

const waveAgents = (w) => w.agents.split('·').length
const wave = (id) => {
  const w = PLAN.waves.find((x) => x.id === id)
  if (!w) throw new Error(`plan-structure has no wave ${id}`)
  return w
}
const waveTip = (id) => {
  const w = wave(id)
  const groups = w.groups.map((g) => g.name).join(' · ')
  return `${w.id} ${w.name} — ${w.agents}. ${groups}. Exit: ${w.exit}`
}

// ── coverage chart ───────────────────────────────────────────────────────────

const mobileBuilt = mobileDesigns - T.designedMobileOwed
const tabletBlocker = (BLOCKERS.blockers.find((b) => b.id === 'BLK-008') || {}).detail || ''

const ROWS = [
  { label: 'Route check exists', v: T.e2eCovered, of: CAPS,
    tip: `${T.e2eCovered} of ${CAPS}. Every registry entry generates its own check: the route renders, in the right shell, with the right permission, with no console error.` },
  { label: 'Renders on desktop', v: T.rendered, of: CAPS,
    tip: `${T.rendered} of ${CAPS} render a real screen; ${T.placeholder} are still placeholders. ${T.referenceOnly} entries are the reference pattern library and ${T.externalDependency} are external dependencies — REFERENCE_ONLY and EXTERNAL_DEPENDENCY by design, not gaps.` },
  { label: 'Asserts real content', v: T.contentAsserted, of: CAPS,
    tip: `${T.contentAsserted} of ${CAPS} checks assert what is on the screen; ${T.renderedWithoutAssertion} confirm a route returned 200 and nothing else. "Returns 200" is the failure mode the Definition of Done names explicitly, and it is now closed.` },
  { label: 'Backed by real data', v: T.dataBacked, of: CAPS,
    tip: `${T.dataBacked} capabilities read the API; ${T.mockOnly} still read fixtures and cannot persist. BLK-004 clears per capability as the backend lands behind the seam, not all at once.` },
  { label: 'Designed mobile built', v: mobileBuilt, of: mobileDesigns,
    tip: `${mobileDesigns} screens ship a structurally different mobile design (table becomes a card list). ${mobileBuilt} are built; ${T.designedMobileOwed} still owe theirs — BLK-006.` },
  { label: 'Tablet verified', v: T.tabletVerified, of: CAPS,
    tip: `BLK-008. ${tabletBlocker || 'Tablet is a first-class target — 768, 820, 834 and 1024, portrait AND landscape.'}` },
  { label: 'Arabic certified', v: T.arabicVerified, of: CAPS,
    tip: `${n(Object.keys(AR).length)} Arabic keys are ported and the primitives use logical CSS properties throughout, so layouts mirror by construction. ${T.arabicVerified} capabilities have been certified for strings, dates, numbers and LTR-pinned Latin runs.` },
  { label: 'RTL certified', v: REG.entries.filter((e) => e.rtl === 'VERIFIED').length, of: CAPS,
    tip: `Direction, icons, chevrons, tables, charts and scroll affordances, certified per capability. ${T.rtlHazards} known RTL hazards remain open in the registry, which is not the same as having checked every screen.` },
  { label: 'Production ready', v: T.productionReady, of: CAPS,
    tip: 'PRODUCTION_READY is the top of an eight-rung status ladder. An agent may mark its own work DONE; only agent 03 sets VERIFIED, and only after re-running the checks rather than reading the claim.' },
]

const X0 = 330, XW = 800, STEP = 48, BAR = 26, TOP = 42
const tone = (r) => (r >= 0.9 ? { fill: 'rgba(218,119,86,0.75)', text: '#DA7756' }
  : r >= 0.5 ? { fill: 'rgba(218,119,86,0.62)', text: '#DA7756' }
  : r >= 0.1 ? { fill: 'rgba(217,184,107,0.7)', text: '#d9b86b' }
  : { fill: 'rgba(224,104,92,0.9)', text: '#f0958c' })

const covRows = ROWS.map((r, i) => {
  const ratio = r.of ? r.v / r.of : 0
  const w = Math.max(3, Math.round(XW * ratio))
  const y = TOP + i * STEP
  const c = tone(ratio)
  return `    <g class="node" data-tip="${esc(r.tip)}">
      <text x="316" y="${y + 18}" text-anchor="end" class="nlabel" style="font-size:14px">${esc(r.label)}</text>
      <rect x="${X0}" y="${y}" width="${w}" height="${BAR}" rx="${w < 8 ? 1.5 : 6}" fill="${c.fill}"/>
      <text x="${X0 + w + 16}" y="${y + 19}" class="nsub" fill="${c.text}">${r.v} / ${r.of}</text>
    </g>`
}).join('\n')
const gridBottom = TOP + (ROWS.length - 1) * STEP + BAR + 18
const axisY = gridBottom + 22
const covH = axisY + 26
const covGrid = [0, 25, 50, 75, 100].map((p) =>
  `      <line x1="${X0 + XW * p / 100}" y1="26" x2="${X0 + XW * p / 100}" y2="${gridBottom}"/>`).join('\n')
const covAxis = [0, 25, 50, 75, 100].map((p) =>
  `<text x="${X0 + XW * p / 100}" y="${axisY}">${p}%</text>`).join('')
const covAria = 'Bar chart of coverage by dimension: ' +
  ROWS.map((r) => `${r.label.toLowerCase()} ${r.v} of ${r.of}`).join(', ') + '.'

// ── blockers ─────────────────────────────────────────────────────────────────

const TAG = { BLOCKER: ['t-block', 'Blocker'], CRITICAL: ['t-crit', 'Critical'],
  HIGH: ['t-high', 'High'], MEDIUM: ['t-med', 'Medium'], LOW: ['t-med', 'Low'] }
const blockerCards = BLOCKERS.blockers.length
  ? BLOCKERS.blockers.map((b) => {
      const [cls, label] = TAG[b.severity] || ['t-med', b.severity]
      return `    <div class="card">
      <span class="tag ${cls}">${esc(label)}</span>
      <h3>${esc(b.title)}</h3>
      <p>${esc(b.detail)}</p>
      <div class="own">${esc(b.id)} · Agent ${esc(b.owner)} · ${esc(b.wave)}</div>
    </div>`
    }).join('\n')
  : `    <div class="card"><span class="tag t-med">Clear</span>
      <h3>No open blockers</h3>
      <p>BLOCKERS.json is computed from the registry, so an empty list means the queries found nothing — not that nobody filed anything.</p>
      <div class="own">BLOCKERS.json · ${esc(day(BLOCKERS.generatedAt))}</div>
    </div>`

// ── golden paths ─────────────────────────────────────────────────────────────

const GP = GOLDEN.totals
/** Three statuses have to be told apart without green, and orange-vs-red alone
 *  is not enough separation at 46px. So the difference is filled vs hollow vs
 *  dashed as well as hue: a passing path is the only solid block on the grid. */
const GP_TONE = {
  PASSING: { fill: 'rgba(218,119,86,0.92)', stroke: '#DA7756', dash: '', ink: '#12100f', text: '#DA7756', panel: 'rgba(218,119,86,0.10)' },
  FAILING: { fill: 'rgba(224,104,92,0.12)', stroke: '#e0685c', dash: '', ink: '#f0958c', text: '#f0958c', panel: 'rgba(224,104,92,0.07)' },
  UNWRITTEN: { fill: 'rgba(255,255,255,0.04)', stroke: 'rgba(255,255,255,0.20)', dash: ' stroke-dasharray="3 3"', ink: '#6f6f79', text: '#8a8a93', panel: 'rgba(255,255,255,0.03)' },
}
const GP_COLS = 8, GP_CW = 46, GP_CH = 30, GP_XS = 56, GP_YS = 40, GP_X = 40, GP_Y = 70
const gpCells = GOLDEN.paths.map((p, i) => {
  const c = GP_TONE[p.status] || GP_TONE.UNWRITTEN
  const x = GP_X + (i % GP_COLS) * GP_XS
  const y = GP_Y + Math.floor(i / GP_COLS) * GP_YS
  const tip = `${p.path} — ${p.status}. ` + (p.error
    ? p.error
    : 'No spec in app/e2e declares this path, so nothing is known about it. Unwritten is not passing.')
  return `      <g class="node" data-tip="${esc(tip)}">
        <rect class="box" x="${x}" y="${y}" width="${GP_CW}" height="${GP_CH}" rx="6" fill="${c.fill}" stroke="${c.stroke}" stroke-width="1.2"${c.dash}/>
        <text x="${x + GP_CW / 2}" y="${y + 20}" text-anchor="middle" class="nsub" fill="${c.ink}" style="font-weight:700">${i + 1}</text>
      </g>`
}).join('\n')
const gpRows = Math.ceil(GOLDEN.paths.length / GP_COLS)
const gpLegendY = GP_Y + gpRows * GP_YS + 26
const gpH = gpLegendY + 44
const gpSummary = [
  ['PASSING', GP.passing, 'A journey walked the product on this run and every assertion held.'],
  ['FAILING', GP.failing, 'A journey ran and the product could not complete the path. RB-03 — "no critical golden-path failure" — is a release blocker.'],
  ['UNWRITTEN', GP.unwritten, 'No journey exists for this path yet, so nothing is known about it. Unwritten is not passing, and it is not failing either.'],
].map(([label, v, tip], i) => {
  const c = GP_TONE[label]
  const x = 640 + i * 180
  return `      <g class="node" data-tip="${esc(`${label}: ${v} of ${GP.paths}. ${tip}`)}">
        <rect class="box" x="${x}" y="${GP_Y - 4}" width="164" height="86" rx="15" fill="${c.panel}" stroke="${c.stroke}" stroke-width="1.5"${c.dash}/>
        <text x="${x + 82}" y="${GP_Y + 34}" text-anchor="middle" class="nbig" fill="${c.text}">${v}</text>
        <text x="${x + 82}" y="${GP_Y + 58}" text-anchor="middle" class="nsub">${label.toLowerCase()}</text>
      </g>`
}).join('\n')
const gpAria = `Grid of ${GP.paths} golden paths measured on ${day(GOLDEN.generatedAt)}: ` +
  `${GP.passing} passing, ${GP.failing} failing, ${GP.unwritten} unwritten.`
const gpFailSample = GOLDEN.paths.filter((p) => p.status === 'FAILING').slice(0, 3)
  .map((p) => p.path).join(', ')

// ── release gates ────────────────────────────────────────────────────────────

const G = GATES.summary
const gateTotal = GATES.gates.length
const gateTip = GATES.gates.map((g) => `${g.id} ${g.title} — ${g.status}`).join(' · ')
const gateFailTitles = GATES.gates.filter((g) => g.status === 'FAIL').map((g) => g.title)
const gateUncheckable = GATES.gates.filter((g) => g.status === 'UNCHECKABLE')
const certLine = GATES.certifiable
  ? 'every gate holds — certifiable'
  : `not certifiable · ${G.FAIL} fail · ${G.UNCHECKABLE} uncheckable`

// ── categories ───────────────────────────────────────────────────────────────

const CATS = PLAN.releaseCategories
const CAT_COLS = 8, CAT_CW = 46, CAT_CH = 30, CAT_XS = 56, CAT_YS = 40, CAT_X = 40, CAT_Y = 70
const catCells = CATS.map((c, i) =>
  `        <rect x="${CAT_X + (i % CAT_COLS) * CAT_XS}" y="${CAT_Y + Math.floor(i / CAT_COLS) * CAT_YS}" width="${CAT_CW}" height="${CAT_CH}" rx="6"/>`
).join('\n')
const catRows = Math.ceil(CATS.length / CAT_COLS)
const catLegendY = CAT_Y + catRows * CAT_YS + 26

// ── RBAC ─────────────────────────────────────────────────────────────────────

const modules = Object.keys(PERMS)
const actions = new Set()
for (const m of Object.values(PERMS)) for (const v of Object.values(m)) for (const ch of String(v)) actions.add(ch)
const ceilings = ROLES.filter((r) => r.limit !== 0)
const unlimited = ROLES.filter((r) => r.limit === null).map((r) => r.label)
const capped = ROLES.filter((r) => typeof r.limit === 'number' && r.limit > 0)
  .sort((a, b) => b.limit - a.limit)
const zero = ROLES.filter((r) => r.limit === 0)
const ceilingStrip = 'SAR ceilings enforced today · ' +
  capped.slice(0, 3).map((r) => `${r.id} ${Math.round(r.limit / 1000)}k`).join(' · ') +
  ` · ${zero.length} roles at 0`
const ceilingTip = 'Approval ceilings, enforced today by canApprove(): ' +
  `${unlimited.join(' and ')} unlimited · ` +
  capped.map((r) => `${r.label} ${n(r.limit)}`).join(' · ') +
  ` · ${zero.map((r) => r.label).join(', ')} 0. ` +
  'The screen states the ceiling up front rather than failing on submit.'

// ── estimates ────────────────────────────────────────────────────────────────

const estDays = EST.buckets.reduce((a, b) => a + b.days, 0)
const estMax = Math.max(...EST.buckets.map((b) => b.days))
/** The bar length is the estimate, so the label sits outside it rather than
 *  inside — a label that must fit would force every bar to the width of its
 *  own text, which is how the hand-written version ended up with bars ordered
 *  by wording instead of by days. Same convention as the coverage chart. */
const EST_X = 40, EST_W = 260, EST_Y = 58, EST_STEP = 42, EST_H = 34
const estBuckets = EST.buckets.map((b, i) => {
  const w = Math.max(10, Math.round(EST_W * (b.days / estMax)))
  const y = EST_Y + i * EST_STEP
  const fill = i < 2 ? `rgba(218,119,86,${0.62 - i * 0.08})`
    : i < 4 ? `rgba(107,164,217,${0.55 - (i - 2) * 0.08})`
    : `rgba(255,255,255,${0.2 - (i - 4) * 0.03})`
  return `    <g class="node" data-tip="${esc(`${b.label} — ${b.days} engineer-days (estimate of ${day(EST.estimatedAt)}). ${b.tip}`)}">
      <rect class="box" x="${EST_X}" y="${y}" width="${w}" height="${EST_H}" rx="8" fill="${fill}" stroke="none"/>
      <text x="${EST_X + w + 14}" y="${y + 23}" class="nsub" style="font-weight:700">${esc(b.label)} · ${b.days}d</text>
    </g>`
}).join('\n')
const EST_SHAPE_TONE = {
  plain: ['rgba(255,255,255,0.04)', 'rgba(255,255,255,0.18)'],
  blue: ['rgba(107,164,217,0.07)', 'rgba(107,164,217,0.45)'],
  accent: ['rgba(218,119,86,0.08)', 'rgba(218,119,86,0.5)'],
}
const shapeY = [58, 206, 354]
const estShapes = EST.shapes.map((s, i) => {
  const [fill, stroke] = EST_SHAPE_TONE[s.tone] || EST_SHAPE_TONE.plain
  const y = shapeY[i] ?? (58 + i * 148)
  return `    <g class="node" data-tip="${esc(`${s.label} — ${s.tip} Estimate of ${day(EST.estimatedAt)}; nothing in the repository computes it.`)}">
      <rect class="box" x="908" y="${y}" width="252" height="70" rx="15" fill="${fill}" stroke="${stroke}"/>
      <text x="1034" y="${y + 32}" text-anchor="middle" class="nlabel" style="font-size:15px">${esc(s.label)}</text>
      <text x="1034" y="${y + 54}" text-anchor="middle" class="nsub">${esc(s.detail)}</text>
    </g>`
}).join('\n')
const estArrows = EST.shapes.map((s, i) => {
  const y = (shapeY[i] ?? (58 + i * 148)) + 35
  const from = 240 + (i - 1) * 24
  return `    <path d="M 670 ${from} C 780 ${from + (y - from) * 0.4}, 830 ${y - (y - from) * 0.15}, 906 ${y}" fill="none" stroke="rgba(218,119,86,0.28)" stroke-width="1.8" marker-end="url(#ar6)"/>
    <path d="M 670 ${from} C 780 ${from + (y - from) * 0.4}, 830 ${y - (y - from) * 0.15}, 906 ${y}" fill="none" stroke="#DA7756" stroke-width="1.8" class="flow"/>`
}).join('\n')

// ── tokens ───────────────────────────────────────────────────────────────────

const TOKENS = {
  // scope
  __CAPS__: CAPS,
  __AGENTS__: PLAN.agents,
  __SURFACES__: surfaces.length,
  __SURFACE_LIST__: surfaceList,
  __DESIGNS__: DESIGN_SCREENS.length,
  __DESIGN_FILES__: designFiles,
  __DESIGN_ENTRIES__: designEntries,
  __MOBILE_DESIGNS__: mobileDesigns,
  __SPECS__: SPEC_SCREENS.length,
  __SPEC_ONLY__: specOnly,
  __OVERLAP__: specOverlap,
  // registry
  __RENDERED__: T.rendered,
  __DATA_BACKED__: T.dataBacked,
  __MOCK_ONLY__: T.mockOnly,
  __E2E__: T.e2eCovered,
  __TABLET__: T.tabletVerified,
  __PROD_READY__: T.productionReady,
  __MOBILE_OWED__: T.designedMobileOwed,
  __ORPHANS__: T.orphanScreenFiles,
  __UNREGISTERED__: T.unregisteredDesigns,
  __REFERENCE_ONLY__: T.referenceOnly,
  __EXTERNAL__: T.externalDependency,
  __RENDER_PCT__: pct(T.rendered, CAPS),
  __DATA_PCT__: pct(T.dataBacked, CAPS),
  __CRUD_READ__: T.crudRead,
  __CRUD_CREATE__: T.crudCreate,
  __CRUD_UPDATE__: T.crudUpdate,
  __CRUD_DELETE__: T.crudDelete,
  __MOCK_TABLES__: MOCK_TABLES,
  // waves
  __WAVES_WORD__: Word(PLAN.waves.length),
  __WAVES_WORD_LC__: word(PLAN.waves.length),
  __W1_AGENTS__: waveAgents(wave('W1')),
  __W1_AGENTS_WORD__: word(waveAgents(wave('W1'))),
  __W2_AGENTS__: waveAgents(wave('W2')),
  __W2_AGENTS_WORD__: Word(waveAgents(wave('W2'))),
  __W0_TIP__: waveTip('W0'),
  __W1_TIP__: waveTip('W1'),
  __W2_TIP__: waveTip('W2'),
  __W3_TIP__: waveTip('W3'),
  __W4_TIP__: waveTip('W4'),
  __W5_TIP__: waveTip('W5'),
  // coverage chart
  __COV_ROWS__: covRows,
  __COV_GRID__: covGrid,
  __COV_AXIS__: covAxis,
  __COV_H__: covH,
  __COV_ARIA__: covAria,
  // blockers
  __BLOCKERS_OPEN__: BLOCKERS.open,
  __BLOCKERS_WORD__: Word(BLOCKERS.open),
  __BLOCKER_CARDS__: blockerCards,
  // golden paths
  __GP_TOTAL__: GP.paths,
  __GP_PASS__: GP.passing,
  __GP_FAIL__: GP.failing,
  __GP_UNWRITTEN__: GP.unwritten,
  __GP_JOURNEYS__: GP.journeys,
  __GP_CELLS__: gpCells,
  __GP_SUMMARY__: gpSummary,
  __GP_LEGEND_Y__: gpLegendY,
  __GP_H__: gpH,
  __GP_ARIA__: gpAria,
  __GP_DATE__: day(GOLDEN.generatedAt),
  // gates
  __GATE_TOTAL__: gateTotal,
  __GATE_TOTAL_WORD__: word(gateTotal),
  __GATE_PASS__: G.PASS,
  __GATE_FAIL__: G.FAIL,
  __GATE_UNCHECKABLE__: G.UNCHECKABLE,
  __GATE_TIP__: gateTip,
  __GATE_FAIL_LIST__: gateFailTitles.join(' · ') || 'none',
  __GATE_UNCHECKABLE_LIST__: gateUncheckable.map((g) => g.title).join(' · ') || 'none',
  __CERT_LINE__: certLine,
  __GATES_DATE__: day(GATES.generatedAt),
  // categories
  __CATEGORIES__: CATS.length,
  __CATEGORIES_WORD__: Word(CATS.length),
  __CATEGORY_CELLS__: catCells,
  __CATEGORY_LIST__: CATS.join(' · '),
  __CATEGORY_SAMPLE__: CATS.slice(0, 4).map((c) => c.toLowerCase()).join(' · ') +
    ' … ' + CATS.slice(-2).map((c) => c.toLowerCase()).join(' · '),
  __CATEGORY_LEGEND_Y__: catLegendY,
  // rbac
  __ROLES__: ROLES.length,
  __MODULES__: modules.length,
  __ACTIONS__: actions.size,
  __CEILING_STRIP__: ceilingStrip,
  __CEILING_TIP__: ceilingTip,
  // estimates
  __EST_DATE__: day(EST.estimatedAt),
  __EST_DAYS__: estDays,
  __EST_BUCKETS__: estBuckets,
  __EST_SHAPES__: estShapes,
  __EST_ARROWS__: estArrows,
  __EST_SHAPES_WORD__: word(EST.shapes.length),
  __EST_UNIT__: EST.unit,
  __EST_EXCLUDED__: EST.excluded,
  __EST_FLOOR__: EST.floorNote,
  __EST_ARIA__: `Fork diagram: an estimated ${estDays} engineer-days remaining, dated ${day(EST.estimatedAt)}, splits into ` +
    EST.shapes.map((s) => `${s.label.toLowerCase()} ${s.detail.replace(/~/g, '')}`).join(', ') + '.',
  // stamps
  __REGISTRY_DATE__: day(REG.generatedAt),
  __BLOCKERS_DATE__: day(BLOCKERS.generatedAt),
  __SERVER_TESTS__: n(GATES.runs.serverSuite.total),
  __MIGRATIONS__: GATES.runs.schemaScan.migrations,
}

// ── render ───────────────────────────────────────────────────────────────────

const templatePath = path.join(here, 'template.html')
let html = fs.readFileSync(templatePath, 'utf8')
/** Longest token first, so __GP_TOTAL__ can never be eaten by a shorter prefix. */
for (const key of Object.keys(TOKENS).sort((a, b) => b.length - a.length)) {
  if (!html.includes(key)) throw new Error(`template is missing ${key}`)
  html = html.split(key).join(String(TOKENS[key]))
}
/** The whole point of the exercise: nothing may reach the page unsubstituted,
 *  and a token left in the template because the generator forgot to define it
 *  is exactly the hardcoded-count defect wearing a disguise. */
const leftover = html.match(/__[A-Z0-9_]+__/g)
if (leftover) throw new Error(`unsubstituted tokens: ${[...new Set(leftover)].join(', ')}`)

/** Writes only when the content actually differs — the same guard
 *  app/scripts/build-registry.mjs uses, minus its stamp mask, which this page
 *  does not need because it prints no wall-clock date. `\r\n` is normalised so
 *  a CRLF checkout does not look like a change. */
const normalise = (t) => t.replace(/\r\n/g, '\n')
const out = path.join(here, 'build-map.html')
const changed = !fs.existsSync(out) || normalise(fs.readFileSync(out, 'utf8')) !== normalise(html)
if (changed) fs.writeFileSync(out, html)
console.log(`build map: ${(html.length / 1024).toFixed(0)} kB · ${Object.keys(TOKENS).length} tokens · ` +
  `${changed ? 'written' : 'unchanged'} → ${path.relative(REPO, out)}`)
console.log(`  registry ${REG.generatedAt} · golden ${GOLDEN.generatedAt.slice(0, 10)} · ` +
  `gates ${GATES.generatedAt.slice(0, 10)} · estimate ${EST.estimatedAt} (human)`)
