import type { DomainScreens } from '../registry'
import {
  UIListView,
  UITableView,
  UICardView,
  UITimelineView,
  UICalendarView,
  UIKanbanView,
  UIMapView,
  UICharts,
  UIActivityFeed,
  UIComments,
  UIAttachments,
  UIMediaGallery,
  UIMessages,
  UIAdvancedFilters,
  UIImportCenter,
  UIExportCenter,
  UIFormValidation,
  UIEmptyStates,
  UILoadingStates,
  UIModalsCRUD,
  UIModalsLifecycle,
  UIModalsStatus,
  UIModalsActions,
  UIModalsData,
  UIModalsCapture,
  FlowSpec,
  ScreenIndex,
  RBACSpec,
} from '../reference'

export const SCREENS: DomainScreens = {
  'UI.ListView': UIListView,
  'UI.TableView': UITableView,
  'UI.CardView': UICardView,
  'UI.TimelineView': UITimelineView,
  'UI.CalendarView': UICalendarView,
  'UI.KanbanView': UIKanbanView,
  'UI.MapView': UIMapView,
  'UI.Charts': UICharts,
  'UI.ActivityFeed': UIActivityFeed,
  'UI.Comments': UIComments,
  'UI.Attachments': UIAttachments,
  'UI.MediaGallery': UIMediaGallery,
  'UI.Messages': UIMessages,
  'UI.AdvancedFilters': UIAdvancedFilters,
  'UI.ImportCenter': UIImportCenter,
  'UI.ExportCenter': UIExportCenter,
  'UI.FormValidation': UIFormValidation,
  'UI.EmptyStates': UIEmptyStates,
  'UI.LoadingStates': UILoadingStates,
  'UI.Modals.CRUD': UIModalsCRUD,
  'UI.Modals.Lifecycle': UIModalsLifecycle,
  'UI.Modals.Status': UIModalsStatus,
  'UI.Modals.Actions': UIModalsActions,
  'UI.Modals.Data': UIModalsData,
  'UI.Modals.Capture': UIModalsCapture,
  FlowSpec,
  Index: ScreenIndex,
  RBACSpec,
}
