/** Enterprise SSO, WebAuthn and social sign-in — adapter interfaces and the
 *  only implementation that is honest today: the unconfigured one.
 *
 *  `API_ENDPOINTS.md` §Auth declares `/auth/sso/start`, `/auth/sso/callback`,
 *  `/auth/biometric/enrol`, `/auth/biometric/challenge`, `/auth/social/:provider`
 *  and the two TOTP routes. None of them has credentials in any environment
 *  this code has run in — there is no identity provider, no relying-party
 *  origin and no OAuth client.
 *
 *  There are two ways to ship that. One is a handler that returns a plausible
 *  looking success, which is how a product reaches production with an
 *  authentication path that authenticates nobody. The other is this: the
 *  contract is defined, the route exists, and it answers **503 with the exact
 *  configuration that is missing**. The endpoint is discoverable, its shape is
 *  fixed, and no reader can mistake it for working.
 *
 *  `status()` is what a deployment check reads, so "which of these are live" is
 *  a question with an answer rather than an archaeology exercise.
 */
import type { AuthConfig } from './config'

export type ProviderId = 'sso' | 'webauthn' | 'social' | 'totp'

export interface ProviderStatus {
  id: ProviderId
  configured: boolean
  /** The environment keys that would make it configured. */
  requires: readonly string[]
  /** What a caller gets today, in words. */
  state: string
}

export class ProviderNotConfigured extends Error {
  readonly provider: ProviderId
  readonly requires: readonly string[]
  constructor(provider: ProviderId, requires: readonly string[], what: string) {
    super(
      `${what} is not configured in this deployment. ` +
        (requires.length ? `Set ${requires.join(', ')} and restart the API. ` : '') +
        'No credential was checked and no session was created.',
    )
    this.name = 'ProviderNotConfigured'
    this.provider = provider
    this.requires = requires
  }
}

/** Enterprise SSO. `start` returns the URL the browser is sent to; `callback`
 *  exchanges the provider's code for a verified identity. */
export interface SsoAdapter {
  readonly configured: boolean
  start(input: { orgSlug: string; redirectUri: string }): Promise<{ redirectUrl: string; state: string }>
  callback(input: { code: string; state: string }): Promise<{ email: string; orgSlug: string }>
}

/** WebAuthn / passkeys. The registration and assertion options are generated by
 *  the relying party, which needs an RP id and an origin to bind them to. */
export interface WebAuthnAdapter {
  readonly configured: boolean
  enrolOptions(input: { userId: string; userName: string }): Promise<unknown>
  challengeOptions(input: { userId: string }): Promise<unknown>
  verifyAssertion(input: { userId: string; assertion: unknown }): Promise<boolean>
}

/** Google and Apple. */
export interface SocialAdapter {
  readonly configured: boolean
  exchange(input: { provider: string; idToken: string }): Promise<{ email: string }>
}

const SSO_KEYS = ['SSO_ISSUER_URL', 'SSO_CLIENT_ID', 'SSO_CLIENT_SECRET'] as const
const WEBAUTHN_KEYS = ['WEBAUTHN_RP_ID', 'WEBAUTHN_ORIGIN'] as const
const SOCIAL_KEYS = ['SSO_CLIENT_ID', 'SSO_CLIENT_SECRET'] as const

export const unconfiguredSso: SsoAdapter = {
  configured: false,
  async start() {
    throw new ProviderNotConfigured('sso', SSO_KEYS, 'Enterprise SSO')
  },
  async callback() {
    throw new ProviderNotConfigured('sso', SSO_KEYS, 'Enterprise SSO')
  },
}

export const unconfiguredWebAuthn: WebAuthnAdapter = {
  configured: false,
  async enrolOptions() {
    throw new ProviderNotConfigured('webauthn', WEBAUTHN_KEYS, 'WebAuthn / biometric sign-in')
  },
  async challengeOptions() {
    throw new ProviderNotConfigured('webauthn', WEBAUTHN_KEYS, 'WebAuthn / biometric sign-in')
  },
  async verifyAssertion() {
    throw new ProviderNotConfigured('webauthn', WEBAUTHN_KEYS, 'WebAuthn / biometric sign-in')
  },
}

export const unconfiguredSocial: SocialAdapter = {
  configured: false,
  async exchange() {
    throw new ProviderNotConfigured('social', SOCIAL_KEYS, 'Social sign-in')
  },
}

export interface Providers {
  sso: SsoAdapter
  webauthn: WebAuthnAdapter
  social: SocialAdapter
}

/** There is exactly one implementation of each adapter and it is the refusing
 *  one. Configuring the environment keys does **not** silently switch a real
 *  adapter on, because no real adapter exists — `providerStatus` says so
 *  separately for "no credentials" and "credentials but no adapter", so a
 *  deployment that sets the keys and still gets a 503 is told why. */
export function buildProviders(): Providers {
  return { sso: unconfiguredSso, webauthn: unconfiguredWebAuthn, social: unconfiguredSocial }
}

export function providerStatus(config: AuthConfig): ProviderStatus[] {
  return [
    {
      id: 'sso',
      configured: false,
      requires: SSO_KEYS,
      state: config.ssoConfigured
        ? 'credentials are present but no SSO adapter is wired; the routes refuse'
        : 'no credentials and no adapter; the routes refuse with 503',
    },
    {
      id: 'webauthn',
      configured: false,
      requires: WEBAUTHN_KEYS,
      state: config.webauthnConfigured
        ? 'a relying party is configured but no WebAuthn adapter is wired; the routes refuse'
        : 'no relying party and no adapter; the routes refuse with 503',
    },
    {
      id: 'social',
      configured: false,
      requires: SOCIAL_KEYS,
      state: 'no adapter; the route refuses with 503',
    },
    {
      id: 'totp',
      configured: false,
      requires: [],
      state:
        'TOTP needs no external credential, but no enrolment store exists on the user record ' +
        'and no adapter is wired in this build; the routes refuse with 503',
    },
  ]
}
