/** Writes the security headers into the three deploy configs.
 *
 *      node scripts/gen-headers.mjs            rewrite the configs
 *      node scripts/gen-headers.mjs --check    fail if they have drifted
 *
 *  The headers are defined once in `app/security-headers.mjs`. nginx, Vercel
 *  and Netlify each want them in a different syntax, and hand-maintaining three
 *  copies of a security policy is how two of them end up a year out of date
 *  while everyone reads the third. The generated regions are fenced by marker
 *  comments so the rest of each file stays hand-written.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { SECURITY_HEADERS } from '../security-headers.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..', '..')
const CHECK = process.argv.includes('--check')

const BEGIN = 'SECURITY HEADERS — generated by app/scripts/gen-headers.mjs'
const END = 'end generated security headers'

const entries = Object.entries(SECURITY_HEADERS)

/** Replace the region between two marker lines, or report that it is missing. */
function splice(source, beginLine, endLine, body) {
  const start = source.indexOf(beginLine)
  const stop = source.indexOf(endLine)
  if (start === -1 || stop === -1 || stop < start) return null
  return source.slice(0, start + beginLine.length) + '\n' + body + source.slice(stop)
}

// ── nginx ───────────────────────────────────────────────────────────────────
// `always` matters: without it nginx omits the header on error responses, so a
// 404 or a 502 would be served with no policy at all.
const nginxBody = entries
  .map(([k, v]) => `    add_header ${k} "${v}" always;`)
  .join('\n')

// ── Vercel ──────────────────────────────────────────────────────────────────
const vercelHeaders = [
  {
    source: '/(.*)',
    headers: entries.map(([key, value]) => ({ key, value })),
  },
]

// ── Netlify ─────────────────────────────────────────────────────────────────
const netlifyBody =
  '[[headers]]\n  for = "/*"\n  [headers.values]\n' +
  entries.map(([k, v]) => `    ${k} = "${v}"`).join('\n')

const targets = []

// nginx.conf — fenced region inside the server block
{
  const file = path.join(ROOT, 'nginx.conf')
  const src = fs.readFileSync(file, 'utf8')
  let next = splice(src, `    # ${BEGIN}`, `    # ${END}`, nginxBody + '\n')
  if (next === null) {
    console.error(`gen-headers: nginx.conf is missing its "${BEGIN}" markers.`)
    process.exit(1)
  }
  /* nginx drops every inherited add_header the moment a nested location
   * declares one of its own, so the static-asset block — which sets
   * Cache-Control — needs the whole set repeated, or it serves the scripts,
   * stylesheets and fonts a CSP most needs to govern with no headers at all. */
  const assetBody = entries
    .map(([k, v]) => `        add_header ${k} "${v}" always;`)
    .join('\n')
  const spliced = splice(
    next,
    `        # ${BEGIN} (asset block)`,
    `        # ${END} (asset block)`,
    assetBody + '\n'
  )
  if (spliced === null) {
    console.error('gen-headers: nginx.conf is missing its asset-block markers.')
    process.exit(1)
  }
  next = spliced
  targets.push({ file, src, next })
}

// vercel.json — whole-file rewrite of the `headers` key, formatting preserved
{
  const file = path.join(ROOT, 'vercel.json')
  const src = fs.readFileSync(file, 'utf8')
  const json = JSON.parse(src)
  json.headers = vercelHeaders
  targets.push({ file, src, next: JSON.stringify(json, null, 2) + '\n' })
}

// netlify.toml — fenced region at the end
{
  const file = path.join(ROOT, 'netlify.toml')
  const src = fs.readFileSync(file, 'utf8')
  const next = splice(src, `# ${BEGIN}`, `# ${END}`, netlifyBody + '\n\n')
  if (next === null) {
    console.error(`gen-headers: netlify.toml is missing its "${BEGIN}" markers.`)
    process.exit(1)
  }
  targets.push({ file, src, next })
}

const drifted = targets.filter((t) => t.src !== t.next)

if (CHECK) {
  if (drifted.length === 0) {
    console.log(`gen-headers: OK — ${entries.length} headers, all three deploy configs in sync.`)
    process.exit(0)
  }
  console.error(
    `\ngen-headers: FAIL — these deploy configs no longer match app/security-headers.mjs:\n` +
      drifted.map((t) => `  ${path.relative(ROOT, t.file)}`).join('\n') +
      `\n\nRun \`npm run gen:headers\` in app/ and commit the result.` +
      `\nA security header that is right in one deployment and stale in another is` +
      `\nworse than one that is missing everywhere, because it reads as covered.\n`
  )
  process.exit(1)
}

for (const t of drifted) fs.writeFileSync(t.file, t.next)
console.log(
  drifted.length === 0
    ? `gen-headers: already up to date — ${entries.length} headers.`
    : `gen-headers: wrote ${entries.length} headers to ${drifted.length} file(s):\n` +
      drifted.map((t) => `  ${path.relative(ROOT, t.file)}`).join('\n')
)
